class LocatorPath():
    male_radio = "/html//input[@id='gender-male']"
    female_radio = "/html//input[@id='gender-female']"
    firstname = "/html//input[@id='FirstName']"
    lastname = "/html//input[@id='LastName']"
    email = "/html//input[@id='Email']"
    password = "/html//input[@id='Password']"
    confirm_password = "/html//input[@id='ConfirmPassword']"
    register_button = "/html//input[@id='register-button']"
    message_after_regis = "//div[contains(text(),'Your registration completed')]"
    error_firstname = "//span[contains(text(),'First name is required.')]"
    error_lastname = "//span[contains(text(),'Last name is required.')]"
    error_email = "//span[contains(text(),'Email is required.')]"
    error_password = "//body/div[4]/div[1]/div[4]/div[2]/form[1]/div[1]/div[2]/div[3]/div[2]/div[1]/span[2]/span[1]"
    continue_button = "//body/div[4]/div[1]/div[4]/div[2]/div[1]/div[2]/div[2]/input[1]"
    logout_link = "//a[contains(text(),'Log out')]"
    username_login = "//input[@id='Email']"
    password_login = "//input[@id='Password']"
    login_button = "//body/div[4]/div[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]/form[1]/div[5]/input[1]"
    welcome = "div.master-wrapper-page:nth-child(4) div.master-wrapper-content div.master-wrapper-main:nth-child(5) div.center-3 div.page.home-page div.page-body div.topic-html-content:nth-child(3) div.topic-html-content-title > h2.topic-html-content-header"
    login_empty = "//span[contains(text(),'Login was unsuccessful. Please correct the errors and try again')]"
    laptop_14inch = "//body/div[4]/div[1]/div[4]/div[3]/div[1]/div[1]/div[3]/div[3]/div[1]/div[2]/h2[1]/a[1]"
    add_laptop_to_cart = "#add-to-cart-button-31"
    shopping_cart = "//span[contains(text(),'Shopping cart')]"
    cart_qty = "div.master-wrapper-page:nth-child(4) div.master-wrapper-content div.header:nth-child(2) div.header-links-wrapper div.header-links ul:nth-child(1) li:nth-child(3) a.ico-cart > span.cart-qty"
    shipping_button = "//body/div[4]/div[1]/div[4]/div[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[4]/input[1]"
    # error_conf_password = "//body/div[4]/div[1]/div[4]/div[2]/form[1]/div[1]/div[2]/div[3]/div[2]/div[2]/span[2]/span[1]"
