class LocatorPath():
    male_radio = "/html//input[@id='gender-male']"
    female_radio = "/html//input[@id='gender-female']"
    firstname = "/html//input[@id='FirstName']"
    lastname = "/html//input[@id='LastName']"
    email = "/html//input[@id='Email']"
    password = "/html//input[@id='Password']"
    confirm_password = "/html//input[@id='ConfirmPassword']"
    register_button = "/html//input[@id='register-button']"
    message_after_regis = "//div[contains(text(),'Your registration completed')]"
    error_firstname = "//span[contains(text(),'First name is required.')]"
    error_lastname = "//span[contains(text(),'Last name is required.')]"
    error_email = "//span[contains(text(),'Email is required.')]"
    error_password = "//body/div[4]/div[1]/div[4]/div[2]/form[1]/div[1]/div[2]/div[3]/div[2]/div[1]/span[2]/span[1]"
    continue_button = "//body/div[4]/div[1]/div[4]/div[2]/div[1]/div[2]/div[2]/input[1]"
    logout_link = "//a[contains(text(),'Log out')]"
    username_login = "//input[@id='Email']"
    password_login = "//input[@id='Password']"
    login_button = "//body/div[4]/div[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]/form[1]/div[5]/input[1]"
    welcome = "//h2[contains(text(),'Welcome to our store')]"
    login_empty = "//span[contains(text(),'Login was unsuccessful. Please correct the errors and try again')]"
    # error_conf_password = "//body/div[4]/div[1]/div[4]/div[2]/form[1]/div[1]/div[2]/div[3]/div[2]/div[2]/span[2]/span[1]"
